// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectA;

namespace ProjectA.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20211026132126_FixDocVersionPrimaryKey")]
    partial class FixDocVersionPrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ProjectA.Models.Document", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SnapshotEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntityId");

                    b.HasIndex("SnapshotEntityId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ProjectA.Models.Document", b =>
                {
                    b.HasOne("ProjectA.Models.Document", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotEntityId");

                    b.OwnsMany("ProjectA.Models.DocVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<int>("EntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("VersionId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("EntityId");

                            b1.ToTable("DocVersion");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");

                            b1.OwnsOne("ProjectA.Models.VersionNumber", "VersionNumber", b2 =>
                                {
                                    b2.Property<Guid>("DocVersionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Major")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Minor")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("DocVersionId");

                                    b2.ToTable("DocVersion");

                                    b2.WithOwner()
                                        .HasForeignKey("DocVersionId");
                                });

                            b1.Navigation("VersionNumber");
                        });

                    b.Navigation("Snapshot");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
